# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e43a0ab41bc2cf8a7363f1401040d46"
name = "loyalty-points-app"
application_url = "https://loyalty-program-production-8f40.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/create"
  topics = [ "customers/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,read_products,read_store_credit_accounts,read_store_credit_account_transactions,write_discounts,write_gift_cards,write_store_credit_account_transactions"

[auth]
redirect_urls = [ "https://loyalty-program-production-8f40.up.railway.app/auth/callback" ]

[app_proxy]
url = "/api/loyalty-balance"
subpath = "loyalty-points"
prefix = "apps"
