// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/hydrogen/customer-reward-history": {
    params: {};
  };
  "/api/customer-account/special-dates": {
    params: {};
  };
  "/api/email-notifications/dispatch": {
    params: {};
  };
  "/api/customer-account/referrals": {
    params: {};
  };
  "/api/customer-account/birthday": {
    params: {};
  };
  "/api/hydrogen/loyalty-balance": {
    params: {};
  };
  "/api/customer-reward-history": {
    params: {};
  };
  "/api/hydrogen/redeem-points": {
    params: {};
  };
  "/api/hydrogen/special-dates": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/create": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/refunds/create": {
    params: {};
  };
  "/api/hydrogen/referrals": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/api/hydrogen/birthday": {
    params: {};
  };
  "/api/birthday-rewards": {
    params: {};
  };
  "/webhooks/orders/paid": {
    params: {};
  };
  "/api/loyalty-balance": {
    params: {};
  };
  "/api/loyalty-balance/api/customer-account/referrals": {
    params: {};
  };
  "/api/loyalty-balance/api/customer-account/birthday": {
    params: {};
  };
  "/api/loyalty-balance/api/customer-reward-history": {
    params: {};
  };
  "/api/loyalty-balance/api/redeem-points": {
    params: {};
  };
  "/api/loyalty-balance/api/birthdays": {
    params: {};
  };
  "/api/loyalty-balance/api/referrals": {
    params: {};
  };
  "/api/loyalty-balance/iframe": {
    params: {};
  };
  "/api/loyalty-program": {
    params: {};
  };
  "/api/loyalty-iframe": {
    params: {};
  };
  "/api/points-expiry": {
    params: {};
  };
  "/api/redeem-points": {
    params: {};
  };
  "/api/special-dates": {
    params: {};
  };
  "/api/test-order": {
    params: {};
  };
  "/api/birthdays": {
    params: {};
  };
  "/api/referrals": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/email-templates": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/customers": {
    params: {};
  };
  "/app/referrals": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/history": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/hydrogen/customer-reward-history" | "/api/customer-account/special-dates" | "/api/email-notifications/dispatch" | "/api/customer-account/referrals" | "/api/customer-account/birthday" | "/api/hydrogen/loyalty-balance" | "/api/customer-reward-history" | "/api/hydrogen/redeem-points" | "/api/hydrogen/special-dates" | "/webhooks/app/scopes_update" | "/webhooks/customers/create" | "/webhooks/app/uninstalled" | "/webhooks/refunds/create" | "/api/hydrogen/referrals" | "/webhooks/orders/create" | "/api/hydrogen/birthday" | "/api/birthday-rewards" | "/webhooks/orders/paid" | "/api/loyalty-balance" | "/api/loyalty-balance/api/customer-account/referrals" | "/api/loyalty-balance/api/customer-account/birthday" | "/api/loyalty-balance/api/customer-reward-history" | "/api/loyalty-balance/api/redeem-points" | "/api/loyalty-balance/api/birthdays" | "/api/loyalty-balance/api/referrals" | "/api/loyalty-balance/iframe" | "/api/loyalty-program" | "/api/loyalty-iframe" | "/api/points-expiry" | "/api/redeem-points" | "/api/special-dates" | "/api/test-order" | "/api/birthdays" | "/api/referrals" | "/auth/login" | "/auth/*" | "/app" | "/app/email-templates" | "/app/additional" | "/app/customers" | "/app/referrals" | "/app/settings" | "/app/history";
  };
  "routes/api.hydrogen.customer-reward-history.jsx": {
    id: "routes/api.hydrogen.customer-reward-history";
    page: "/api/hydrogen/customer-reward-history";
  };
  "routes/api.customer-account.special-dates.jsx": {
    id: "routes/api.customer-account.special-dates";
    page: "/api/customer-account/special-dates";
  };
  "routes/api.email-notifications.dispatch.jsx": {
    id: "routes/api.email-notifications.dispatch";
    page: "/api/email-notifications/dispatch";
  };
  "routes/api.customer-account.referrals.jsx": {
    id: "routes/api.customer-account.referrals";
    page: "/api/customer-account/referrals";
  };
  "routes/api.customer-account.birthday.jsx": {
    id: "routes/api.customer-account.birthday";
    page: "/api/customer-account/birthday";
  };
  "routes/api.hydrogen.loyalty-balance.jsx": {
    id: "routes/api.hydrogen.loyalty-balance";
    page: "/api/hydrogen/loyalty-balance";
  };
  "routes/api.customer-reward-history.jsx": {
    id: "routes/api.customer-reward-history";
    page: "/api/customer-reward-history";
  };
  "routes/api.hydrogen.redeem-points.jsx": {
    id: "routes/api.hydrogen.redeem-points";
    page: "/api/hydrogen/redeem-points";
  };
  "routes/api.hydrogen.special-dates.jsx": {
    id: "routes/api.hydrogen.special-dates";
    page: "/api/hydrogen/special-dates";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.create.jsx": {
    id: "routes/webhooks.customers.create";
    page: "/webhooks/customers/create";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.refunds.create.jsx": {
    id: "routes/webhooks.refunds.create";
    page: "/webhooks/refunds/create";
  };
  "routes/api.hydrogen.referrals.jsx": {
    id: "routes/api.hydrogen.referrals";
    page: "/api/hydrogen/referrals";
  };
  "routes/webhooks.orders.create.jsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/api.hydrogen.birthday.jsx": {
    id: "routes/api.hydrogen.birthday";
    page: "/api/hydrogen/birthday";
  };
  "routes/api.birthday-rewards.jsx": {
    id: "routes/api.birthday-rewards";
    page: "/api/birthday-rewards";
  };
  "routes/webhooks.orders.paid.jsx": {
    id: "routes/webhooks.orders.paid";
    page: "/webhooks/orders/paid";
  };
  "routes/api.loyalty-balance.jsx": {
    id: "routes/api.loyalty-balance";
    page: "/api/loyalty-balance" | "/api/loyalty-balance/api/customer-account/referrals" | "/api/loyalty-balance/api/customer-account/birthday" | "/api/loyalty-balance/api/customer-reward-history" | "/api/loyalty-balance/api/redeem-points" | "/api/loyalty-balance/api/birthdays" | "/api/loyalty-balance/api/referrals" | "/api/loyalty-balance/iframe";
  };
  "routes/api.loyalty-balance.api.customer-account.referrals.jsx": {
    id: "routes/api.loyalty-balance.api.customer-account.referrals";
    page: "/api/loyalty-balance/api/customer-account/referrals";
  };
  "routes/api.loyalty-balance.api.customer-account.birthday.jsx": {
    id: "routes/api.loyalty-balance.api.customer-account.birthday";
    page: "/api/loyalty-balance/api/customer-account/birthday";
  };
  "routes/api.loyalty-balance.api.customer-reward-history.jsx": {
    id: "routes/api.loyalty-balance.api.customer-reward-history";
    page: "/api/loyalty-balance/api/customer-reward-history";
  };
  "routes/api.loyalty-balance.api.redeem-points.jsx": {
    id: "routes/api.loyalty-balance.api.redeem-points";
    page: "/api/loyalty-balance/api/redeem-points";
  };
  "routes/api.loyalty-balance.api.birthdays.jsx": {
    id: "routes/api.loyalty-balance.api.birthdays";
    page: "/api/loyalty-balance/api/birthdays";
  };
  "routes/api.loyalty-balance.api.referrals.jsx": {
    id: "routes/api.loyalty-balance.api.referrals";
    page: "/api/loyalty-balance/api/referrals";
  };
  "routes/api.loyalty-balance.iframe.jsx": {
    id: "routes/api.loyalty-balance.iframe";
    page: "/api/loyalty-balance/iframe";
  };
  "routes/api.loyalty-program.jsx": {
    id: "routes/api.loyalty-program";
    page: "/api/loyalty-program";
  };
  "routes/api.loyalty-iframe.jsx": {
    id: "routes/api.loyalty-iframe";
    page: "/api/loyalty-iframe";
  };
  "routes/api.points-expiry.jsx": {
    id: "routes/api.points-expiry";
    page: "/api/points-expiry";
  };
  "routes/api.redeem-points.jsx": {
    id: "routes/api.redeem-points";
    page: "/api/redeem-points";
  };
  "routes/api.special-dates.jsx": {
    id: "routes/api.special-dates";
    page: "/api/special-dates";
  };
  "routes/api.test-order.jsx": {
    id: "routes/api.test-order";
    page: "/api/test-order";
  };
  "routes/api.birthdays.jsx": {
    id: "routes/api.birthdays";
    page: "/api/birthdays";
  };
  "routes/api.referrals.jsx": {
    id: "routes/api.referrals";
    page: "/api/referrals";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/email-templates" | "/app/additional" | "/app/customers" | "/app/referrals" | "/app/settings" | "/app/history";
  };
  "routes/app.email-templates.jsx": {
    id: "routes/app.email-templates";
    page: "/app/email-templates";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.customers.jsx": {
    id: "routes/app.customers";
    page: "/app/customers";
  };
  "routes/app.referrals.jsx": {
    id: "routes/app.referrals";
    page: "/app/referrals";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.history.jsx": {
    id: "routes/app.history";
    page: "/app/history";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.hydrogen.customer-reward-history": typeof import("./app/routes/api.hydrogen.customer-reward-history.jsx");
  "routes/api.customer-account.special-dates": typeof import("./app/routes/api.customer-account.special-dates.jsx");
  "routes/api.email-notifications.dispatch": typeof import("./app/routes/api.email-notifications.dispatch.jsx");
  "routes/api.customer-account.referrals": typeof import("./app/routes/api.customer-account.referrals.jsx");
  "routes/api.customer-account.birthday": typeof import("./app/routes/api.customer-account.birthday.jsx");
  "routes/api.hydrogen.loyalty-balance": typeof import("./app/routes/api.hydrogen.loyalty-balance.jsx");
  "routes/api.customer-reward-history": typeof import("./app/routes/api.customer-reward-history.jsx");
  "routes/api.hydrogen.redeem-points": typeof import("./app/routes/api.hydrogen.redeem-points.jsx");
  "routes/api.hydrogen.special-dates": typeof import("./app/routes/api.hydrogen.special-dates.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.customers.create": typeof import("./app/routes/webhooks.customers.create.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.refunds.create": typeof import("./app/routes/webhooks.refunds.create.jsx");
  "routes/api.hydrogen.referrals": typeof import("./app/routes/api.hydrogen.referrals.jsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.jsx");
  "routes/api.hydrogen.birthday": typeof import("./app/routes/api.hydrogen.birthday.jsx");
  "routes/api.birthday-rewards": typeof import("./app/routes/api.birthday-rewards.jsx");
  "routes/webhooks.orders.paid": typeof import("./app/routes/webhooks.orders.paid.jsx");
  "routes/api.loyalty-balance": typeof import("./app/routes/api.loyalty-balance.jsx");
  "routes/api.loyalty-balance.api.customer-account.referrals": typeof import("./app/routes/api.loyalty-balance.api.customer-account.referrals.jsx");
  "routes/api.loyalty-balance.api.customer-account.birthday": typeof import("./app/routes/api.loyalty-balance.api.customer-account.birthday.jsx");
  "routes/api.loyalty-balance.api.customer-reward-history": typeof import("./app/routes/api.loyalty-balance.api.customer-reward-history.jsx");
  "routes/api.loyalty-balance.api.redeem-points": typeof import("./app/routes/api.loyalty-balance.api.redeem-points.jsx");
  "routes/api.loyalty-balance.api.birthdays": typeof import("./app/routes/api.loyalty-balance.api.birthdays.jsx");
  "routes/api.loyalty-balance.api.referrals": typeof import("./app/routes/api.loyalty-balance.api.referrals.jsx");
  "routes/api.loyalty-balance.iframe": typeof import("./app/routes/api.loyalty-balance.iframe.jsx");
  "routes/api.loyalty-program": typeof import("./app/routes/api.loyalty-program.jsx");
  "routes/api.loyalty-iframe": typeof import("./app/routes/api.loyalty-iframe.jsx");
  "routes/api.points-expiry": typeof import("./app/routes/api.points-expiry.jsx");
  "routes/api.redeem-points": typeof import("./app/routes/api.redeem-points.jsx");
  "routes/api.special-dates": typeof import("./app/routes/api.special-dates.jsx");
  "routes/api.test-order": typeof import("./app/routes/api.test-order.jsx");
  "routes/api.birthdays": typeof import("./app/routes/api.birthdays.jsx");
  "routes/api.referrals": typeof import("./app/routes/api.referrals.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.email-templates": typeof import("./app/routes/app.email-templates.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.customers": typeof import("./app/routes/app.customers.jsx");
  "routes/app.referrals": typeof import("./app/routes/app.referrals.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.history": typeof import("./app/routes/app.history.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};